version: '3.3'
services:
  pyhtmlgenpdf:
    container_name: pyhtmlgenpdf
    build: .
    image: pyhtmlgenpdf:latest
    restart: always

    labels:
      - traefik.enable=true
      - traefik.http.routers.pyhtmlgenpdf-http.entrypoints=web
      - traefik.http.routers.pyhtmlgenpdf-http.rule=Host(`pyhtmlgenpdf.staging.helpwritingresumes.com`)
      - traefik.http.routers.pyhtmlgenpdf-http.middlewares=pyhtmlgenpdf-redirect-to-https
      # HTTPS router
      - traefik.http.routers.pyhtmlgenpdf-https.entrypoints=web-secured
      - traefik.http.routers.pyhtmlgenpdf-https.rule=Host(`pyhtmlgenpdf.staging.helpwritingresumes.com`)
      - traefik.http.routers.pyhtmlgenpdf-https.tls=true
      - traefik.http.routers.pyhtmlgenpdf-https.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.pyhtmlgenpdf-redirect-to-https.redirectscheme.scheme=https
    ports:
      - "5000:5000"

networks:
  default:
    external:
      name: proxy
